### ISSUE TITLE
Is function decapitalize correct ?

### ISSUE THREAD

**Issue by Yeskendir1993** [appzcoder/30-seconds-of-php-code#28] opened 2018-07-29 12:32 UTC
function decapitalize($string, $upperRest = false)
{
    return strtolower(substr($string, 0, 1)) . ($upperRest ? strtoupper(substr($string, 1) : substr($string, 1));
}

function decapitalize($string, $upperRest = false)
{
    return strtolower(substr($string, 0, 1)) . ($upperRest ? strtoupper(substr($string, 1))  : substr($string, 1));
}

**Comment by sohelamin** [comment] 2018-07-29 15:18
@Yeskendir1993 Did you found any issue? If yes then please share the expected output here.

**Comment by peter279k** [comment] 2018-07-31 02:13
It should provide the test cases to know where the problem is :+1: .

**Comment by peter279k** [comment] 2018-08-04 07:13
This issue should be closed because it's fixed via this PR #29 .

**Closed** 2018-08-04 07:30 UTC
